### ISSUE TITLE
Payment method "bank transfer"

### ISSUE THREAD

**Issue by peerdicken** [Attendize/Attendize#118]
Is there any easy way to enable a bank transfer payment, where users would pay with normal bank transfer (iban,bic) and then after the payment has been registered, the order could be processed?

**Comment by ylecuyer** [comment]
I think we should add the possibility to manually create an order as it is possible for an attendee (but I renamed it invite see #117) so that it would be possible to process it manually after receiving payment.
If the bank provide an API it would be possible to process the order automatically

cc @daveearley

**Comment by daveearley** [comment]
@peerdicken currently offline payment methods aren't available, however, the option will be added soon. Most likely similar to how [Eventbrite do it] (https://www.eventbrite.ie/support/articles/en_US/How_To/how-to-accept-payments-by-check-invoice-or-at-the-event-with-offline-payments?lg=en_IE).

@ylecuyer Yes I agree, as it stands now manually creating attendees creates a new order each time, so it would be good to have a 'create order' option with the ability to have several attendees under the same order.

**Comment by wamserma** [comment]
I vote up. Offline payments are crucial for my use case (small event with about 80 participants).

**Comment by daveearley** [comment]
Merging with issue #8

**Comment by daveearley** [comment]
Basic support for offline payments have been added today.
