### ISSUE TITLE
Booking not registering

### ISSUE THREAD

**Issue by angrydogmedi** [Attendize/Attendize#275]
Getting error message
"Whoops!, it looks like the server returned an error. Please try again, or contact the webmaster if the problem persists." after submitting a booking this is both with free and paid events,

With paid events(using stripe) the payment does go through, just nothing registering on the system,

it has me at a loss why, no logs are registering either and debug is set to true, 
im at a total loss

**Comment by jharris70** [comment]
I have a similar issue: payments would be processed, and the Whoops error appeared. I figured it was something that I changed when I wasn't looking! The absence of the error log is disappointing, though.

I added an alert panel to the payment page telling people of the false positive error and to wait for a payment receipt before trying again, but some people still just don't read and we ended up refunding multiple charges.

**Comment by ungelovende** [comment]
I'm having the same problem. And when I check the Chrome console I get a Error 500 Internal server error when I try to buy a ticket, the same error even if I try with a free ticket.
But I do not understand why it's a error 500 error, everything els working?

It happen when I use Stripe payment or if I use Offline payment.

**Comment by daveearley** [comment]
Hey @ungelovende ,

Try setting **APP_DEBUG=true** in your **.env**, you should see the full error then.

**Comment by ungelovende** [comment]
@daveearley I've already set true - but doesn't show any logs in "storage/logs"

**Comment by daveearley** [comment]
Is there any error other than the one above coming back from the ajax call in the dev tools?

**Comment by ungelovende** [comment]
No. Just som warnings about some decoding fonts.

I get the same error in attendize when I try to invite a person with a ticket.
dev console show: "POST http://domian.tld/event/12/attendees/resend_ticket 500 (Internal Server Error)"

**Comment by daveearley** [comment]
In that case it could be that your email setup is the problem as there are email being sent when you carry out those actions. Can you post the full response from the AJAX calls?

**Comment by ungelovende** [comment]
When I try to resend a ticket for invitee it says "Whoops!, it looks like the server returned an error." in the browser, the dev console in chrome say "jquery.js:8630 POST http://domain.tld/public/event/12/attendees/resend_ticket 500 (Internal Server Error)"
dev console:
POST http://domain.tld.no/event/12/attendees/resend_ticket 500 (Internal Server Error)
send @ jquery.js:8630
ajax @ jquery.js:8166
$.fn.ajaxSubmit @ backend.js:4179
doAjaxSubmit @ backend.js:4776
dispatch @ jquery.js:4435
r.handle @ jquery.js:4121

When I try to book a ticket from front end I get this:
"Whoops!, it looks like the server returned an error. Please try again, or contact the webmaster if the problem persists."

dev console:
POST http://domain.tld/e/2/checkout/create 500 (Internal Server Error)
send @ frontend.js:3
ajax @ frontend.js:3
$.fn.ajaxSubmit @ frontend.js:2355
(anonymous) @ frontend.js:4699
dispatch @ frontend.js:2
r.handle @ frontend.js:2


I can add that I can't download PDF-ticket either, seems like the creation of PDF files doesn't work.
I getting a error page, see the attatchment.
[pdf-ticket.txt](https://github.com/Attendize/Attendize/files/712187/pdf-ticket.txt)

**Comment by daveearley** [comment]
from the error in the pdf-ticket.txt it seems WKHTML2PDF is the issue. Have you looked at the [troubleshooting section related to WKHTML2PDF](https://attendize.com/documentation.php#troubleshooting)? it may help you

**Comment by ungelovende** [comment]
Yes. I've done that already.
The only thing I can think of, my host is running a Ubuntu version of Linux, and you only refer to Debian - could that be the problem?

**Comment by daveearley** [comment]
It could be, I'm not overly familiar with Wkhtml2PDF so can't be too certain. Try googling "WKHTMLTOPDF didn't return any data", many people seem to come across the same issue.

**Comment by D3vStAr** [comment]
Has anyone solved this issue? I have the same problem. Application works 100% in php artisan serve with localhost:8000 but as soon as on is dev.runtv.co.za check out fails. http://dev.runtv.co.za/e/1/boksburg-fun-run

Inspector returns frontend.js:3 POST http://dev.runtv.co.za/e/1/checkout/create 500 (Internal Server Error)
send @ frontend.js:3
ajax @ frontend.js:3
$.fn.ajaxSubmit @ frontend.js:2355
(anonymous) @ frontend.js:4699
dispatch @ frontend.js:2
r.handle @ frontend.js:2

And then gives the famous "Whoops something gone wrong" but the ticket order is in the system and all notification email are sent successfully so the system successfully adds a ticket sale but does not show order confirmation.

**Comment by CongdonJL** [comment]
Getting the same issue as @D3vStAr

**Comment by D3vStAr** [comment]
I altered the frontend.js file in  under assets to out out the returned data to the Console 

` error: function(data, statusText, xhr, $form) {
                        $submitButton = $form.find('input[type=submit]');

                      // Form validation error.
                        if (422 == data.status) {
                            processFormErrors($form, $.parseJSON(data.responseText));
                            return;
                        }
                        
			window.console&&console.log(data);
			window.console&&console.log(statusText);
			window.console&&console.log(xhr);
						
                        toggleSubmitDisabled($submitButton);
                        showMessage('Whoops!, it looks like the server returned an error.\n\
                   Please try again, or contact the webmaster if the problem persists yea.');
                    },`

The out put was the following 
`
frontend.js:3 POST http://dev.runtv.co.za/e/2/checkout/create 500 (Internal Server Error)
{readyState: 4, getResponseHeader: ƒ, getAllResponseHeaders: ƒ, setRequestHeader: ƒ, overrideMimeType: ƒ, …}
abort:ƒ (a)
always:ƒ ()
complete:ƒ ()
done:ƒ ()
error:ƒ ()
fail:ƒ ()
getAllResponseHeaders:ƒ ()
getResponseHeader:ƒ (a)
overrideMimeType:ƒ (a)
pipe:ƒ ()
progress:ƒ ()
promise:ƒ (a)
readyState:4
responseText:
"[2018-06-01 06:31:28] local.INFO: Firing the event  ↵↵[2018-06-01 06:31:28] local.INFO: Begin Processing Order: YTCTM16  
[2018-06-01 06:31:28] local.INFO: Generating ticket: #YTCTM16  
[2018-06-01 06:31:28] local.INFO: {"id":98,"account_id":1,"order_status_id":1,"created_at":"2018-06-01 06:31:28","updated_at":"2018-06-01 06:31:28","deleted_at":null,"first_name":"Keith","last_name":"Kennedy","email":"email@test.co.za","ticket_pdf_path":null,"order_reference":"YTCTM16","transaction_id":null,"discount":"0.00","booking_fee":"0.00","organiser_booking_fee":"0.00","order_date":null,"notes":null,"is_deleted":0,"is_cancelled":0,"is_partially_refunded":0,"is_refunded":0,"amount":"0.00","amount_refunded":null,"event_id":2,"payment_gateway_id":null,"is_payment_received":1} 

[2018-06-01 06:31:28] local.INFO: Ticket generated!  
[2018-06-01 06:31:28] local.INFO: Generating ticket: #YTCTM16 

[2018-06-01 06:31:28] local.INFO: Use ticket from cache: C:\inetpub\wwwroot\peakevents\public\user_content/pdf_tickets/YTCTM16.pdf  

[2018-06-01 06:31:28] local.INFO: Sending ticket to carl: email@test.co.za  
[2018-06-01 06:32:04] local.INFO: Sending ticket Order Info: Keith@peaktiming.co.za"
setRequestHeader:ƒ (a,b)
stateƒ ()
status:500
statusCodeƒ (a)
statusText:"Internal Server Error"
success:ƒ ()
then:ƒ (__proto__
:Object

`

Could the problem be the system is returning the log info reports instead of the OK 200 response?

**Comment by CongdonJL** [comment]
Any update to this?

**Comment by zzbyasb** [comment]
Not sure what’s wrong, but i set up Stripe to receive test transactions and i see tons of test come through fine. I get the Whoops errror and no ticket or order is created, but when i check the error log i get the below error. It seems like it stopped at creating the transaction_id. I know the Faker stuff works because it was used for order numbers. What would cause this?

[2018-07-16 06:47:08] production.INFO: {"id":124,"account_id":1,"order_status_id":1,"created_at":"2018-07-16 06:47:08","updated_at":"2018-07-16 06:47:08","deleted_at":null,"first_name":”TestName","last_name":"TestName","email":"testemail@yahoo.com","ticket_pdf_path":null,"order_reference":"V9EJL167","transaction_id

**Comment by jeremyquinton** [comment]
Closing this issue for now as #429 has been merged.
