### ISSUE TITLE
Transaction rollback if email not sent after ticket purchase

### ISSUE THREAD

**Issue by jshailes** [Attendize/Attendize#306]
Upon successfully purchasing a ticket via Paypal, the pdf is generated and attempted to be sent out via email. If the email fails to send due to bad credentials it seems the order data is not persisted to the database. Nginx error log attached.
[emailNotSent.txt](https://github.com/Attendize/Attendize/files/749918/emailNotSent.txt)

**Comment by daveearley** [comment]
Hi @jshailes, The problem seems to [occur here ](https://github.com/Attendize/Attendize/blob/87fb3ad4b2352cdd32eae2ff8dbf1fdcc747565e/app/Http/Controllers/EventCheckoutController.php#L610-L610). Usually the send email/PDF generation is passed off to a queue, so if something fails the order is still generated. Unfortunately if Attendize is set to run without a queue bad email credentials etc. will cause the whole order to fail. In v2 I'll revisit this to make sure orders won't be lost :+1:

**Comment by jeremyquinton** [comment]
Once #429 is merged what will happen is the order will be created in the database. However if the ticket can't be generated and the attendee email can't be sent this does not affect the order being persisted in the database. Going to close this ticket for now.

**Comment by jeremyquinton** [comment]
Closing this issue as #429 has been merged.
