### ISSUE TITLE
Manually check-in for attendees. 

### ISSUE THREAD

**Issue by iamchetanp** [Attendize/Attendize#477]
Is there anyway to do manually check-in for attendees. Instead of QR.

**Comment by publicarray** [comment]
Yes, just click on the table row.

**Comment by iamchetanp** [comment]
I tried it. But it was showing attendee already checked out. When I refresh it reverted to original.

**Comment by publicarray** [comment]
Can you open the dev console and look in the network tab. Do you get an ok status (200) code?
![screen shot 2018-10-02 at 7 10 16 am](https://user-images.githubusercontent.com/5497998/46316066-64f09700-c612-11e8-827d-ed76109ee8af.png)

**Comment by iamchetanp** [comment]
When I check I get only one request chekin 

`{status: "error", message: "Attendee Already Checked Out!", checked: "out", id: 9475}
checked: "out"
id: 9475
message: "Attendee Already Checked Out!"
status: "error`

and after refresh it is showing already selected. Ref. [Example](http://attendize.website/event/5121/check_in)

**Comment by GamfaleanuVlad** [comment]
Heyo, I seem to have stumble upon this problem. All my attendees are already green when I enter Check In, when clicking on any of them I get "Attendee Already Checked Out!", and when refreshing everything resets to the green state. The scanner does say correctly if it scanned multiple times, and in the database I am seeing the correct arrival time/null if not checked in yet. I am not really familiar with this attendize, but I can debug more or less myself, I would just need a hand in finding a general point in the right direction.

**Comment by GamfaleanuVlad** [comment]
In the meantime, I found a cause, and a bodge fix : 
It is because somewhere in the pipepline, attendee.has_arrived is being parsed from int to string an thus being truthy when being checked in check_in.js and CheckIn.blade.php

My fix was to parse it back into int and then into boolean (https://stackoverflow.com/a/16313488)

check_in.js:
![image](https://github.com/Attendize/Attendize/assets/56848417/c9cb16aa-65c3-4338-b52c-26da740de53b)

 CheckIn.blade.php:
![image](https://github.com/Attendize/Attendize/assets/56848417/a207ffd1-5d66-485a-8eff-adf6ef49e043)

I don't know the underlying cause, but if will look into it when I have time.
