### ISSUE TITLE
Rewrite issue in Attendize v.1.1.2 in Sub Directory install

### ISSUE THREAD

**Issue by GaneshKandu** [Attendize/Attendize#510]
Hi,

I am getting  404 Error
``Sorry, the page you are looking for could not be found.``

I have Installed Attendize v.1.1.2 in Sub Directory of Web root

``http://domain.com/manual/attendize112`` is URL
``/home/user/www/manual/attendize112`` this is install path of Attendize v.1.1.2
``/home/user/www/`` is webroot

.htaccess must rewrite url to ``http://domain.com/manual/attendize112/public`` on access of ``http://domain.com/manual/attendize112``

**Comment by pccolella** [comment]
Had the same issue in Apache after setting up an alias for serving from a subdirectory. The problem lies in the .htaccess in the public folder. Replace with this and it should solve your problem:

# The following rule tells Apache that if the requested filename
# exists, simply serve it.
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [L]
# The following rewrites all other queries to index.php. The
# condition ensures that if you are using Apache aliases to do
# mass virtual hosting or installed the project in a subdirectory,
# the base path will be prepended to allow proper resolution of
# the index.php file; it will work in non-aliased environments
# as well, providing a safe, one-size fits all solution.
RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
RewriteRule ^(.*) - [E=BASE:%1]
RewriteRule ^(.*)$ %{ENV:BASE}/index.php [L]

**Comment by pccolella** [comment]
`# The following rule tells Apache that if the requested filename
# exists, simply serve it.
RewriteCond %{REQUEST_FILENAME} -s [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [L]
# The following rewrites all other queries to index.php. The
# condition ensures that if you are using Apache aliases to do
# mass virtual hosting or installed the project in a subdirectory,
# the base path will be prepended to allow proper resolution of
# the index.php file; it will work in non-aliased environments
# as well, providing a safe, one-size fits all solution.
RewriteCond %{REQUEST_URI}::$1 ^(/.+)/(.*)::\2$
RewriteRule ^(.*) - [E=BASE:%1]
RewriteRule ^(.*)$ %{ENV:BASE}/index.php [L]`
