### ISSUE TITLE
Error installing through Docker: Unable to find image 'attendize_composer:latest' locally

### ISSUE THREAD

**Issue by ahassoun** [Attendize/Attendize#788]
I am trying to install Attendize using the Docker method.

All steps up to docker-compose build are successful. With those last few lines of 'docker-compose build' output:

```
Removing intermediate container 81e7eebb2e12
 ---> afd7ef690475
Step 6/8 : RUN mkdir /etc/nginx/snippets
 ---> Running in 9b24ea327708
Removing intermediate container 9b24ea327708
 ---> d7b612e6f8bd
Step 7/8 : COPY self-signed.conf /etc/nginx/snippets/self-signed.conf
 ---> 21812f49a56a
Step 8/8 : COPY ssl-params.conf /etc/nginx/snippets/ssl-params.conf
 ---> 4f21fb494ade
Successfully built 4f21fb494ade
Successfully tagged events_web:latest
```

And this is the step I am trying to do next with the error I am getting:

```
# docker run --rm -it -v $(pwd):/usr/share/nginx/html/attendize attendize_composer composer install
Unable to find image 'attendize_composer:latest' locally
docker: Error response from daemon: pull access denied for attendize_composer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

**Comment by samdb** [comment]
Can you paste the output of what is displayed when you run:
`docker ps`

**Comment by ahassoun** [comment]
> Can you paste the output of what is displayed when you run:
> `docker ps`

None. Only headers:

# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

**Comment by samdb** [comment]
That shows no containers are running so executing the run command won't do anything. Try running:
`docker-compose up`
and then do the docker run command again.

**Comment by ahassoun** [comment]
docker-compose up finished with 2 errors:

```
Creating events_db_1      ... error
Creating events_redis_1   ... 
WARNING: Host is already in use by another container

Creating events_maildev_1 ... done
Creating events_redis_1   ... done

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint events_db_1 (4e49e4cd0accba1d14538bdf0c65a3bd85e225c977947d9cd81c004735a850a0): Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use
ERROR: Encountered errors while bringing up the project.
```

**Comment by johannac** [comment]
@ahassoun that is fine to use your local database instead of the docker one that failed to start. Given the command output you pasted, all the other containers should have started successfully and you can ignore the error about the database container. 

The previous/original error of unable to find image - this has to do with name of the container when it was built, which will default to the name of the directory it's in. In your case it looks like you've cloned the code into `events/` which means the container will be called `events_composer`. 

I'm going to go ahead and close this issue since I don't see a bug happening here. The errors are related to running the correct docker commands, which you can find more information about in the docker and docker-compose documentation. Thanks!
