### ISSUE TITLE
[BUG] image attendize_worker not found when using docker-compose

### ISSUE THREAD

**Issue by makayabou** [Attendize/Attendize#806]
I'm trying to install Attendize using docker-compose.
However, I clone the project and run docker-compose and I get this error message:
```ERROR: pull access denied for attendize_worker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied```

Has image been moved?

Thanks

**Comment by johannac** [comment]
Hi @makayabou could you paste the exact docker commands you are running please?

**Comment by makayabou** [comment]
Hello, i'm using docker-compose with:
`docker-compose up -d`
I did not make any change to default docker-compose.yml in project

**Comment by johannac** [comment]
@makayabou ah ok, you'll want to build the images first. See the `make build` command in the Makefile for the exact syntax. Otherwise using docker-compose it will not build all the image stages in the Dockerfile. 

If you are on a *nix style OS, including mac, you can just run `make setup` and it will do all the build and run commands for you. See the docs here https://www.attendize.com/getting_started.html#running-attendize-in-docker-for-development

**Comment by makayabou** [comment]
Oups sorry for not having RTFM !
that's better with make!
I had however to change open to xdg-open in Makefile.
Thank you!
closing now

**Comment by johannac** [comment]
No worries, glad it's working now!
