### ISSUE TITLE
[BUG] buying a license not possible

### ISSUE THREAD

**Issue by bastelix** [Attendize/Attendize#863]
**cannot buy a license**
I want to use attendize as a base for a small product. please can you make me offer for a license please. on the website it is not possible to buy.

please contact me, I was sending your support an email also.

**Comment by bastelix** [comment]
another option is, to give them project an other license(GPL, MIT ...) and I will sell for yearly support - this would be the best option to give the project a real chance

**Comment by bastelix** [comment]
Why is it not possible to by a license? I payed a month ago by paypal and nobody is answering. Is there still support at this project? Do I get my money back or is someone send me license document? My order number was #AGCL-418673

**Comment by Louis312** [comment]
Hello, Did you manage to buy the licence?

**Comment by bastelix** [comment]
Not really. Have payed and never got an license document for my client. I have developed a lot cool stuff for attendize, but it seems license model and worst support will stop the future of this project. Support does not exist.

**Comment by bastelix** [comment]
If someone is interessting in a complete German translated and company internal modified attendize system. Pls write me.

**Comment by Louis312** [comment]
I am interested in Spanish version of attedize system.

Who is selling?

**Comment by justynpride** [comment]
@bastelix I'd be interested in finding out what additions you have made to the system. There are a number of features I've been looking for. How best to contact you?

**Comment by johannac** [comment]
@Louis312 yes, there was just a temporary issue with our payment provider stripe when this ticket was originally opened, but that has been resolved and you can purchase licenses on our web site here https://www.attendize.com/license.html. Also Spanish translations are available by default. 

@bastelix please note that you purchased a Standard Licence and it does not come with support. Also please note that none of our licences allow for redistribution. You can read more on our website https://www.attendize.com/license.html.

**Comment by bastelix** [comment]
I have never get a license sheet, an invoice or a a document what I can use official. I have wrote a lot of emails to get a license document. I t does no matter if this is standard license. The support should get me a document that I have payed and can use license at my customer domain. This is the only support I need. my invoice for example.

**Comment by bastelix** [comment]
> @bastelix I'd be interested in finding out what additions you have made to the system. There are a number of features I've been looking for. How best to contact you?

calhelp.de

**Comment by Louis312** [comment]
Hello, 
Can you tell me how long does it take from the payment to receive the code?
Regards,
Luis



De: Johanna Cherry
Enviado: sábado, 27 de marzo de 2021 16:41
Para: Attendize/Attendize
CC: Louis312; Mention
Asunto: Re: [Attendize/Attendize] [BUG] buying a license not possible (#863)

@Louis312 yes, there was just a temporary issue with our payment provider stripe when this ticket was originally opened, but that has been resolved and you can purchase licenses on our web site here https://www.attendize.com/license.html. Also Spanish translations are available by default.
@bastelix please note that you purchased a Standard Licence and it does not come with support. Also please note that none of our licences allow for redistribution. You can read more on our website https://www.attendize.com/license.html.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
El software de antivirus Avast ha analizado este correo electrónico en busca de virus.
https://www.avast.com/antivirus

**Comment by bastelix** [comment]
I have never got a license document. A code is not needed. To hide license tags you need to comment it out in code.

⁣regards

Am 28. März 2021, 11:34, um 11:34, Louis312 ***@***.***> schrieb:
>
>Hello, 
>Can you tell me how long does it take from the payment to receive the
>code?
>Regards,
>Luis
>
>
>
>De: Johanna Cherry
>Enviado: sábado, 27 de marzo de 2021 16:41
>Para: Attendize/Attendize
>CC: Louis312; Mention
>Asunto: Re: [Attendize/Attendize] [BUG] buying a license not possible
>(#863)
>
>@Louis312 yes, there was just a temporary issue with our payment
>provider stripe when this ticket was originally opened, but that has
>been resolved and you can purchase licenses on our web site here
>https://www.attendize.com/license.html. Also Spanish translations are
>available by default.
***@***.*** please note that you purchased a Standard Licence and it does
