### ISSUE TITLE
Payment

### ISSUE THREAD

**Issue by Louis312** [Attendize/Attendize#887]
Hello, 
Can anyone tell me how long does it take from the payment to receive the code?
Regards,

**Comment by bastelix** [comment]
Which code you mean Louis? A code is not needed. To hide license tags you need to comment it out in code. The problem is, that you don ´t get any validation document, that you can do this. I have not a license document or an invoice or any official information that I can use as license document since I bought my license month ago.

**Comment by Louis312** [comment]
Everything solved. Thank you
