### ISSUE TITLE
Customers charged multiple times

### ISSUE THREAD

**Issue by GeekLabsUK** [Attendize/Attendize#982]
**Describe the bug**
We have now had chance to test this system properly and it is now being used in a live environment where upwards of 10,000 tickets will be sold over the next 6 weeks. We have sold over 800 in last week and have noticed a recurring problem.

We had an order come through and it had repeated itself and charged the customer 4 times. The payment had gone through stripe, new tickets and new orders were created. We thought it was a one off but it has happened at least 6 times now, each time the customers order getting repeated 4 times and being charged 4 times. With the refund / cancel tickets also experiencing a bug where we can not cancel an order all refunds are having to be processed manually and the orders deleted directly from within phpmyadmin.

**Comment by storca** [comment]
I have this issue too, customers are charged multiple times if they click too fast on the pay button.

This is because a request has to be made on click (```postCreateOrder```) and the response of this requests changes the usability of the button accordingly.

But when experiencing high traffic, requests take longer to process and the pay button is still active when the request is being processed by Attendize.
Then customers think that their click did not work and try it once or twice again.

Regarding refunding with Stripe SCA, you should try the [following fix](https://github.com/storca/Attendize/commit/213d8081d895ad748ea62d96b97dd9550d62df10).
The PR for Stripe SCA is #1016 

I'm looking into fixing the issue with this button that is still active but it implies either changing some aspects of the way order are created or using a html/js trick.
